/**
 * export.ts — download helpers for a customised SKILL.md.
 *
 * Three export paths, picked by the user from the customizer's done
 * state:
 *
 *   downloadSkillBundle   A zip containing SKILL.md, INSTALL.md, and
 *                         CUSTOMIZATION-NOTES.md. User unzips into
 *                         ~/.claude/skills/<slug>/ and Claude Code
 *                         picks the skill up.
 *   buildInstallOneLiner  A one-line bash command (uses a heredoc)
 *                         that writes the customised SKILL.md into
 *                         ~/.claude/skills/<slug>/SKILL.md on the
 *                         user's machine. Pasteable into a terminal.
 *   buildInstallNotesMd   Markdown that records what was customised
 *                         for provenance — included in the zip.
 *
 * We don't pull JSZip statically. It's only needed when the user
 * clicks 'Download zip', so we dynamic-import to keep the main
 * customizer bundle small.
 */

export interface ExportInput {
  skillSlug: string;
  skillName: string;
  skillDepartment: string;
  /** Repo-relative path to the original SKILL.md, e.g. departments/foo/skills/bar/SKILL.md */
  sourcePath: string;
  /** The customised SKILL.md content produced by the LLM. */
  customisedSkillMd: string;
  /** The original SKILL.md content (as on GitHub) for the notes file. */
  originalSkillMd: string;
  /** User's environment context captured at customization time. */
  techStack: string;
  scale: string;
  constraints: string;
  extraPrompt: string;
  /** Model used for the run. */
  modelLabel: string;
  modelId: string;
}

/** Build a shell one-liner that writes the SKILL.md to ~/.claude/skills/<slug>/. */
export function buildInstallOneLiner(input: ExportInput): string {
  // Heredoc with a quoted sentinel ('SDAS_SKILL_EOF') so no interpolation
  // happens inside — the customised content goes through verbatim.
  // mkdir -p is idempotent; the second command writes the file.
  const lines: string[] = [];
  lines.push(`mkdir -p ~/.claude/skills/${input.skillSlug}`);
  lines.push(
    `cat > ~/.claude/skills/${input.skillSlug}/SKILL.md <<'SDAS_SKILL_EOF'`,
  );
  lines.push(input.customisedSkillMd.trimEnd());
  lines.push(`SDAS_SKILL_EOF`);
  return lines.join("\n");
}

/** Provenance markdown bundled into the zip. */
export function buildInstallNotesMd(input: ExportInput): string {
  const ts = new Date().toISOString();
  const env = [
    input.techStack ? `- Tech stack: ${input.techStack}` : null,
    input.scale && input.scale !== "unspecified" ? `- Scale: ${input.scale}` : null,
    input.constraints ? `- Constraints: ${input.constraints}` : null,
    input.extraPrompt ? `- Extra instructions: ${input.extraPrompt}` : null,
  ]
    .filter(Boolean)
    .join("\n");

  return `# Customization notes — ${input.skillName}

Generated by **skillkit.dev** customizer on ${ts}.

## Source

- Original SKILL.md: [${input.sourcePath}](https://github.com/tahirraufkeeyu/software-development-agent-stack--sdas/blob/main/${input.sourcePath})
- Department: \`${input.skillDepartment}\`
- Slug: \`${input.skillSlug}\`

## Model

- ${input.modelLabel} (\`${input.modelId}\`) via OpenRouter

## Environment captured

${env || "- (none provided)"}

## How to install

Drop the accompanying \`SKILL.md\` into \`~/.claude/skills/${input.skillSlug}/SKILL.md\`.
Or run the one-line install command shown on skillkit.dev right after generation.

## Reverting

If the customisation doesn't work out, re-install the upstream version:

\`\`\`bash
cd ~/.claude/skills
rm -rf ${input.skillSlug}
# then from the SDAS repo:
./install.sh ${input.skillDepartment}
\`\`\`
`;
}

/** Minimal INSTALL.md included in the zip. */
function buildInstallMd(input: ExportInput): string {
  return `# Install

1. Locate your Claude Code skills directory. By default this is:

   \`\`\`
   ~/.claude/skills/
   \`\`\`

2. Create a folder for this skill:

   \`\`\`bash
   mkdir -p ~/.claude/skills/${input.skillSlug}
   \`\`\`

3. Move the included \`SKILL.md\` into that folder:

   \`\`\`bash
   mv SKILL.md ~/.claude/skills/${input.skillSlug}/
   \`\`\`

4. Restart Claude Code if it's running — it picks up new skills on startup.

See CUSTOMIZATION-NOTES.md for how this skill was customised and how to revert.
`;
}

/**
 * Download a zip with SKILL.md + INSTALL.md + CUSTOMIZATION-NOTES.md.
 * Dynamic-imports JSZip so the library isn't paid for on page load —
 * only when the user actually downloads.
 */
export async function downloadSkillBundle(input: ExportInput): Promise<void> {
  // @ts-expect-error runtime import (jszip doesn't ship its own bundler types
  //   in a shape Vite resolves by default under our tsconfig).
  const JSZipModule = await import("jszip");
  const JSZip = JSZipModule.default ?? JSZipModule;

  const zip = new JSZip();
  zip.file("SKILL.md", input.customisedSkillMd);
  zip.file("INSTALL.md", buildInstallMd(input));
  zip.file("CUSTOMIZATION-NOTES.md", buildInstallNotesMd(input));

  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = `${input.skillSlug}-customised.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/** Copy a string to the clipboard with a graceful fallback. */
export async function copyToClipboard(text: string): Promise<boolean> {
  if (navigator.clipboard?.writeText) {
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch {
      // Fall through to the textarea trick.
    }
  }
  try {
    const ta = document.createElement("textarea");
    ta.value = text;
    ta.setAttribute("readonly", "");
    ta.style.position = "absolute";
    ta.style.left = "-10000px";
    document.body.appendChild(ta);
    ta.select();
    const ok = document.execCommand("copy");
    document.body.removeChild(ta);
    return ok;
  } catch {
    return false;
  }
}
